language: node_js

node_js:
- stable

before_install:
- npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

before_script:
- DEBUG=eslint:cli-engine npm run lint:all
- npm run build

deploy:
#- provider: script
#  script: npm run publish:canary -- --yes
#  skip_cleanup: true
#  on:
#    tags: false
#    branch: master
#    repo: kirill-konshin/next-redux-wrapper
- provider: script
  script: npm run publish:fromgit -- --yes
  skip_cleanup: true
  on:
    tags: true
    repo: kirill-konshin/next-redux-wrapper

after_success:
- npm run test:coverage