language: node_js

cache:
  directories:
    - node_modules

node_js:
- stable

before_install:
- npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

before_script:
- DEBUG=eslint:cli-engine npm run lint:all
- npm run build

deploy:
- provider: script
  script: npm run publish:release -- ${TRAVIS_TAG} --yes
  skip_cleanup: true
  on:
    tags: true
    repo: kirill-konshin/next-redux-wrapper

after_success:
- npm run test:coverage