language: node_js
node_js:
- latest
deploy:
  provider: npm
  email: kirill.konshin@gmail.com
  api_key:
    secure: S2u0xl8LlEIncuXiDxUAwA/wrmzCFMAsog0lycv7IzklB1QMhaxUaeftcy0IyeKxa8qgiR0Spj/a2sfEayxwSglrJT/Wu961OLKnzQhaQwqKYO/CoudVMtvRu2eQSKKJVLTBG6LP6kosLTb7fGrpz1BJXZIO47VnE585XgBxQmmyKP1P0YJGiXy2JCC99suNTna4gPWAmeQM5t8XsymrQff3ZDxWmMEZRrSqRipZalQCGRTNN1hLR3lI/oZQ+5we7UBUDLcMVz40ynXncuVf0uxeuKCDqVcEtvE45rBbUVElyYVSds/+B4Blckrn90tonL3zp13G+78cL219XRhecQLSJQwIPd6/x8qRAX7axn0aZAgq7+QHafNaZFSgCHW+Zi36cul+naOwXrXANXdIucKF/e5ZdHUJBspn+yWy9IgPBMQwvXH/qBWwtqz47GEN9pn8XRL+He5a3QCqh66wA+rxSLnuXULYAXyIN8HG2IMyISiexKb33FVNRlxUWqaBIv3GRxZpA7BvHcDAwZr093ZVey/qHSzCfkmFG0BlDQrYpxjy58JR6TxRMcwbepJavGPmjga2cc5JDNBp5Xr77B418CgvCbdfyAbzz6whUDC7uvuCjN38oN7eVA84LkO8s5Yse9bwZjXQEJIRgzs9e+JKtJ41pLFs4nNaUJ1cTbY=
  skip_cleanup: true
  on:
    tags: true
    repo: kirill-konshin/next-redux-wrapper