language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: kirill.konshin@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: kirill-konshin/next-redux-wrapper